services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  api:
    image: husseinserag/pipeline-email-ai-backend:latest

    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "3000:3000"

volumes:
  redis_data:
