version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis

    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"] # Enables persistence

    volumes:
      - redis_data:/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    image: api
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app

volumes:
  redis_data:
