name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Download env file from s3
        run: aws s3 cp s3://${{ secrets.S3_BUCKETNAME }}/.env /home/ubuntu/.env; pwd

      - name: navigate to deployment dir
        run: cd /home/ubuntu

      - name: Log in to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p ${{ secrets.DOCKER_PASSWORD }}

      - name: start docker containers
        run: |
          sudo docker compose down
          sudo docker compose pull
          sudo docker compose up
