name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Docker cleanup
        run: |

          sudo docker container stop pipeline-email-ai-backend-container
          sudo docker container stop redis 
          sudo docker container rm pipeline-email-ai-backend-container
          sudo docker container rm redis
          sudo docker network rm app 
          sudo docker container prune -f
          sudo docker image prune -af
          sudo docker volume prune -f
          sudo docker network prune -f

      - name: Download env file from s3
        run: aws s3 cp s3://${{ secrets.S3_BUCKETNAME }}/.env /home/ubuntu/.env; pwd

      - name: navigate to deployment dir
        run: cd /home/ubuntu

      - name: start docker containers
        run: |
          docker compose down
          docker compose pull
          docker compose build
          docker compose up
