name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/pipeline-email-ai-backend:latest .
      - name: Push to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/pipeline-email-ai-backend:latest
